### ISSUE TITLE
query re: changing constructor defaults & semver

### ISSUE THREAD

**Issue by SignpostMarv** [paragonie/hidden-string#3]
Would changing the constructor defaults to disable inline / serialisation be a sufficiently breaking change that'd it'd require a 2.x release ?

**Comment by SignpostMarv** [comment]
p.s. I have a vague feeling I may have asked this previously...

**Comment by paragonie-security** [comment]
We're already considering a breaking change for #2 so if you want to roll that into a v2 release that only supports PHP 7.4+, that would be a good time to do it.
