### ISSUE TITLE
PHP 8 Support

### ISSUE THREAD

**Issue by Brunty** [paragonie/hidden-string#4]
Hey, opening an issue to get some ideas about how you'd feel WRT putting in a PR to support PHP 8?

It'd mean bumping the versions of psalm and PHPUnit up for the dev dependencies.

If it's something you're interested in, I can look at putting a PR in over the weekend!

**Comment by paragonie-security** [comment]
This was done in `v1.1.0`.

(We're in the process of updating most of our open source libraries to support PHP 8 this week.)

**Comment by Brunty** [comment]
@paragonie-security oh, cool! Thanks! 👍
